name: Build Super Meat Boy

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java Code
      run: |
        # Change this if your folder is named differently in GitHub
        cd SupermeatBoy
        
        mkdir -p out
        find src -name "*.java" > sources.txt
        javac -d out @sources.txt

    - name: Package into Executable JAR
      run: |
        cd SupermeatBoy
        
        jar cfe SuperMeatBoy.jar app.MeatBoyFrame -C out .

    - name: Upload Playable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SuperMeatBoy-Release
        # Update these paths to match the cd command above
        path: |
          SupermeatBoy/SuperMeatBoy.jar
          SupermeatBoy/resources/
